# Generated by Django 3.2.4 on 2021-06-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0003_questionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionModel',
        ),
    ]
