# Generated by Django 3.2.4 on 2021-06-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0005_contactusmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroduceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('youtubeLink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RepresentativeIntroductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('contentImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('content1', models.CharField(max_length=10000)),
                ('content2', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
    ]
