# Generated by Django 3.2.4 on 2021-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0007_questionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducemodel',
            name='content',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
