# Generated by Django 3.2.4 on 2021-06-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0009_alter_introducemodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introducemodel',
            name='content',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
