# Generated by Django 3.2.4 on 2021-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0010_alter_introducemodel_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepresentativeIntroductionModel',
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='content',
            field=models.CharField(max_length=100, verbose_name='문의내용'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='email',
            field=models.CharField(max_length=50, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='introducemodel',
            name='content',
            field=models.TextField(max_length=200, verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='introducemodel',
            name='youtubeLink',
            field=models.CharField(max_length=200, verbose_name='유튜브링크'),
        ),
    ]
