# Generated by Django 3.2.4 on 2021-06-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0011_auto_20210622_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepresentativeIntroductionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='대표자이름')),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='썸네일 사진')),
                ('contentImage', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='본문 사진')),
                ('current_history', models.TextField(max_length=10000, verbose_name='현재 이력')),
                ('past_history', models.TextField(max_length=10000, verbose_name='과거 이력')),
                ('qualification', models.TextField(max_length=10000, verbose_name='자격 내용')),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
