# Generated by Django 3.2.4 on 2021-06-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0014_auto_20210622_0552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepresentativeIntroductionModel',
        ),
    ]
