# Generated by Django 3.2.4 on 2021-06-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0016_representativeintroductionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceModel',
        ),
    ]
