# Generated by Django 3.2.4 on 2021-06-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0017_delete_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='서비스 이름')),
                ('profileImage', models.ImageField(upload_to='images', verbose_name='서비스 사진')),
                ('content', models.TextField(max_length=10000, verbose_name='서비스 내용')),
            ],
        ),
    ]
