# Generated by Django 3.2.4 on 2021-06-21 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0018_servicemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
