# Generated by Django 3.2.4 on 2021-06-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0021_auto_20210622_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images', verbose_name='로고 이미지')),
                ('content', models.TextField(max_length=100, verbose_name='내용')),
            ],
            options={
                'verbose_name': '바닥 페이지',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': '상담받기 페이지',
            },
        ),
    ]
