# Generated by Django 3.2.4 on 2021-06-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happyWorkShop', '0022_footermodel_questionmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterModel',
        ),
    ]
